# docker-compose.yml
# https://docs.docker.com/compose/compose-file/compose-file-v3/
version: '3'

# https://hub.docker.com/r/drone/drone/tags?page=1&ordering=last_updated
services:
  gitea:
    image: gitea/gitea:latest
    ports:
      - ${GITEA_HOST_PORT}:3000
      - ${GITEA_HOST_SSH_PORT}:22
    volumes:
      - /var/lib/gitea:/data
    restart: always

  drone-server:
    image: drone/drone:2.0.1
    ports:
      - ${DRONE_HOST_HTTP_PORT}:80
    volumes:
      - ./:/var/lib/drone/
    restart: always
    environment:
      - DRONE_SERVER_HOST=${DRONE_SERVER_HOST}
      - DRONE_SERVER_PROTO=${DRONE_SERVER_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}

      # Gitea Config
      - DRONE_GITEA_CLIENT_ID=${DRONE_GITEA_CLIENT_ID}
      - DRONE_GITEA_CLIENT_SECRET=${DRONE_GITEA_CLIENT_SECRET}
      - DRONE_GITEA_SERVER=${DRONE_GITEA_SERVER}

# https://hub.docker.com/r/drone/agent/tags?page=1&ordering=last_updated
  drone-agent:
    image: drone/drone-runner-docker:1
    restart: always
    depends_on:
      - drone-server
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_HOST=drone-server
      - DRONE_RPC_PROTO=${DRONE_RPC_PROTO}
      - DRONE_RPC_SECRET=${DRONE_RPC_SECRET}
